### PR TITLE
Improved Plant Harvesting

### PR DESCRIPTION
**Pull request by Elliott-Smith**
Significantly improved the plant harvesting mechanic.
The item will now fall towards the player and automatically enter their inventory if it is not full.
The item will fall on the ground if their inventory is full.

### CODE REVIEW

**Comment by enemeez** [comment]
Thought about implementing this originally, but wanted to keep Vanilla feel. Probably will make this a config option

**Comment by Elliott-Smith** [comment]
Yea, although they get stuck up on the trees sometimes so I thought it might be useful. Do you want me to make it configurable for you?

**Comment by enemeez** [comment]
No worries – I need to clean up the CustomCrop and Config class beforehand

**Comment by Elliott-Smith** [comment]
Cool let me know when it's ready

**Comment by enemeez** [comment]
A couple of errors I ran into:
1. Firstly, I had to revert the way right-click harvesting worked on all crops because of a mistake I made with a client-side method, so you will have to work around that again
2. I ran into issues having right-click harvesting as a config option. Even if the boolean was set to false for harvesting, crops could still be right-clicked and dropped items correctly

With this in mind, if you can make another pr avoiding the new conflicts with change (1) and try to make it configurable in the FeatureConfig class like you offered, that would be fantastic.

**Comment by Elliott-Smith** [comment]
Sure thing I'll see what I can do. Closing this request.

**Pull request closed without merging**
