### PR TITLE
1.18.2 Port

### PR DESCRIPTION
**Pull request by Rover656**
[We're gonna need a new branch]

This is an initial port to 1.18.2, things seem to work, but we're gonna need testing. I'm linking a JAR here for testers :)

Things that have been done:
- Upgraded the gradle project to 1.18.2 forge
- Remapped from MCP to Mojmap using [Forge-Class-Remapper](https://github.com/SizableShrimp/Forge-Class-Remapper)
- Fixed compilation errors (moved methods, new tags)
- Changed to deferred registries, 1.18.2 changed when freezing happens, to make sure everything happens at the right time we're using deferred registries now. Read more [here](https://mcforge.readthedocs.io/en/latest/concepts/registries/)
- Rewrote world generation. This is done by reading the decompiled Minecraft code to see how vegetation generation code is. The custom features (the placers for bushes etc.) were all still working, they just needed to be moved to a new method overload.
- Fixed the voxel shapes in the brewing barrel, the parameters were the wrong way and were causing an exception.
- Fixed advancements. They changed it from having a single item ID to having a list of item ids in the inventory_changed trigger. See [here](https://minecraft.fandom.com/wiki/Advancement/JSON_format#minecraft:inventory_changed) for documentation on the format.

In future data generation would be a good idea. Right now all JSON data is manually filled in, this can cause problems if a format changes or you want to change a block/item name.

I'll unmark this as draft once testers come back with some feedback.

### CODE REVIEW

**Comment by Rover656** [comment]
Testing JAR for people: [Updated with up to commit 224b5a3c8843a4883ecb31d6c409774a36bb447b]:
[simplefarming-1.18.2-1.4.0.zip](https://github.com/cweckerl/simplefarming/files/8192403/simplefarming-1.18.2-1.4.0.zip)

**Comment by Trzezwosc** [comment]
good job bro

**Comment by Rover656** [comment]
Hoping to get a little time this weekend to try and test crop growth versus 1.16 so i can get this done and ready to merge.

**Comment by jackhidalgos** [comment]
Hello I could only find an error but before that the generation is perfect the designs of the fruits and the dishes excellent your work I loved and here the error I don't know if it only happened to me but the mod fails immediately when combined with others (Example : Jei or Optifine).

**Comment by Wuzzle** [comment]
Hey, this port's terrain generation conflicts with Immersive Engineering's generation

**Comment by Wuzzle** [comment]
Bug report, oats don't seem to drop from their respective crop

**Comment by Wuzzle** [comment]
Okay actual bug report this time, this port is causing one of the music discs (Nourish) to play randomly on the jukebox layer as if it was an overworld ambient song

**Comment by Rover656** [comment]
This port is unmaintained, as it was superceded by 1.19 support. Feel free to use this jar at your own peril, but I won't be fixing things anymore :)

**Pull request closed without merging**
